# backend/docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: muradmanapov
      POSTGRES_PASSWORD: Murad001
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - app/config/.env
    depends_on:
      - db
