"""first migrate

Revision ID: 34bf2f16a66b
Revises: 
Create Date: 2025-04-25 15:22:12.678215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34bf2f16a66b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=50), nullable=False),
    sa.Column('transliteration', sa.String(length=100), nullable=False),
    sa.Column('name_ru', sa.String(length=100), nullable=False),
    sa.Column('tafsir', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='name_ru'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('names', schema='name_ru')
    # ### end Alembic commands ###
