"""New model form card learning

Revision ID: 4fed3b76b66f
Revises: 34bf2f16a66b
Create Date: 2025-05-02 18:59:04.009394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fed3b76b66f'
down_revision: Union[str, None] = '34bf2f16a66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ar', sa.String(length=50), nullable=False),
    sa.Column('transliteration', sa.String(length=100), nullable=False),
    sa.Column('name_ru', sa.String(length=100), nullable=False),
    sa.Column('tafsir', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='name_ru'
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='name_ru'
    )
    op.create_table('learning_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('easiness', sa.Float(), nullable=False),
    sa.Column('interval', sa.SmallInteger(), nullable=False),
    sa.Column('repetitions', sa.SmallInteger(), nullable=False),
    sa.Column('last_reviewed', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.CheckConstraint("mode IN (\n            'transcription_to_translation',\n            'arabic_to_translation',\n            'translation_to_arabic',\n            'translation_to_transcription'\n            )", name='check_learning_mode'),
    sa.ForeignKeyConstraint(['name_id'], ['name_ru.names.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['name_ru.users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name_id', 'mode', name='uq_user_name_mode'),
    schema='name_ru'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_progress', schema='name_ru')
    op.drop_table('users', schema='name_ru')
    op.drop_table('names', schema='name_ru')
    # ### end Alembic commands ###
